"""initial tables

Revision ID: 61d898f041a9
Revises: 
Create Date: 2026-01-17 18:52:02.317613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d898f041a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='存储路径'),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='文档类型'),
    sa.Column('period', sa.String(length=20), nullable=True, comment='报表期间'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='公司名称'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='处理状态'),
    sa.Column('indicators', sa.JSON(), nullable=True, comment='财务指标'),
    sa.Column('raw_markdown', sa.Text(), nullable=True, comment='解析后的Markdown'),
    sa.Column('balance_check_passed', sa.Integer(), nullable=True, comment='勾稽校验是否通过'),
    sa.Column('confidence', sa.String(length=20), nullable=True, comment='置信度'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, comment='审计状态'),
    sa.Column('risk_score', sa.Float(), nullable=True, comment='风险评分 0-100'),
    sa.Column('violations', sa.JSON(), nullable=True, comment='违规列表'),
    sa.Column('reasoning_chain', sa.JSON(), nullable=True, comment='推理链'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='纠偏重试次数'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=True, comment='报告格式'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='生成状态'),
    sa.Column('file_path', sa.String(length=512), nullable=True, comment='报告文件路径'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('audits')
    op.drop_table('documents')
    # ### end Alembic commands ###
